// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/(app)/access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/access">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/bracket/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bracket">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/bracket/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/entry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/entry">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/entry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/event/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/event">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/event/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/foursomes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/foursomes">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/foursomes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/grouping/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/grouping">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/grouping/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leaderboard">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/organization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organization">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/organization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/prizes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prizes">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/prizes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/qualification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/qualification">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/qualification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/registration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registration">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/registration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/roster/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/roster">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/roster/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/scorecard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/scorecard">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/scorecard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/scoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/scoring">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/scoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/series/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/series">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/series/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/stages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stages">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/stages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/teams/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teams">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/teams/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/choose/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/choose">> = Specific
  const handler = {} as typeof import("../../src/app/choose/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/live/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/live/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/live/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/play/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/play">> = Specific
  const handler = {} as typeof import("../../src/app/play/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/styleguide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styleguide">> = Specific
  const handler = {} as typeof import("../../src/app/styleguide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
