import { landingTokens } from "@/lib/landing-palette";

/**
 * The front door's stylesheet, shared by `/` and `/faq`, scoped under `.thq`.
 *
 * Redesigned 2026-09-29 — the "Swiss poster" direction Ajay chose from three
 * (with the interactive screen panel from another): a warm white page, near-black
 * type set big, ONE bold colour, and the real product shown large. No gradients,
 * no glows, no card-on-card; hierarchy comes from type size and space.
 *
 *  - ORANGE is identity: the last word of the headline, the times of day, the
 *    highlighted plan, the "five reasons" band. GREEN is meaning only — live,
 *    under par — and the TourneyHQ lockup keeps its own fixed colours.
 *  - A DARK BAND (`.band`) is the same components on the dark palette: it
 *    re-declares the tokens, so a card, a button or a table inside it needs no
 *    second set of rules.
 *
 * EVERY COLOUR IS GENERATED by `landing-palette.ts`, which solves each text
 * colour against the grounds it is read on; `landing-contrast.test.ts` grades
 * both palettes and reads this file to prove no colour is written by hand.
 * `black` and `white` appear only for physical objects — the phone bezel, the
 * store badges — and in shadows.
 *
 * Animation baselines live behind `.thq-js` (added by LandingEffects), so with
 * JavaScript off the page is fully visible, and every tab, filter and slider is
 * a native control that works without it.
 */
export const LANDING_CSS = `
.thq, .thq * { box-sizing: border-box; }
.thq {
  color-scheme: light;
${landingTokens("light", "  ")}
  --card: var(--panel);
  /* The lockup is the app's own, drawn the same everywhere (Ajay, 2026-09-29:
     "fix the logo to be consistent all across"). Its flagstick and cup read the
     page's ink here, as they read the app's text colour there; the pennant and
     ball keep TourneyHQ's fixed orange and green. */
  --logo-stick: var(--ink); --logo-cup: var(--ink-soft);
  --wash: color-mix(in srgb, var(--ink) 4%, transparent);
  --wash-2: color-mix(in srgb, var(--ink) 8%, transparent);
  --accent-a12: color-mix(in srgb, var(--brass-ui) 12%, transparent);
  --flag-a: color-mix(in srgb, var(--flag) 14%, transparent);
  --shadow: 0 1px 0 rgba(0,0,0,.03), 0 24px 48px -28px rgba(0,0,0,.28);
  --shadow-xl: 0 0 0 1px rgba(0,0,0,.06), 0 50px 90px -40px rgba(0,0,0,.4);
  --sans: var(--font-geist-sans), -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, system-ui, sans-serif;
  --mono: var(--font-geist-mono), ui-monospace, "SFMono-Regular", Menlo, Consolas, monospace;
  --ease: cubic-bezier(.32,.72,0,1);
  --wrap: 1240px;
  --r: 22px;
  font: 400 17px/1.6 var(--sans); background: var(--ground); color: var(--ink);
  -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;
  overflow-x: clip; min-height: 100vh;
}
/* The same components on the dark palette. */
.thq .band {
  color-scheme: dark;
${landingTokens("dark", "  ")}
  --card: color-mix(in srgb, var(--ground-2) 70%, var(--ground));
  --logo-stick: var(--ink); --logo-cup: var(--ink-soft);
  --shadow: 0 24px 48px -28px rgba(0,0,0,.8);
  background: var(--ground); color: var(--ink);
}
.thq :where(h1,h2,h3,h4,p,ul,ol,figure,dl,dd) { margin: 0; padding: 0; }
/* The app's own caption rule (design-system.css: 11px, text at 55%) is written
   for the app's dark ground; on this white page it painted the format boards'
   titles near-white on white, 1.02:1, and nobody could read them. */
.thq figcaption { font-size: inherit; margin-top: 0; color: inherit; }
.thq ul { list-style: none; }
.thq a { color: inherit; text-decoration: none; }
.thq svg { display: block; flex: none; }
.thq img { max-width: 100%; height: auto; display: block; }
.thq :focus-visible { outline: 2px solid var(--brass-ui); outline-offset: 3px; border-radius: 6px; }
.thq .sr { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0 0 0 0); white-space: nowrap; margin: -1px; padding: 0; border: 0; }
.thq .wrap { max-width: var(--wrap); margin: 0 auto; padding-left: max(40px, env(safe-area-inset-left)); padding-right: max(40px, env(safe-area-inset-right)); }
@media (max-width: 760px) { .thq .wrap { padding-left: max(20px, env(safe-area-inset-left)); padding-right: max(20px, env(safe-area-inset-right)); } .thq { font-size: 16.5px; } }
.thq .i { width: 20px; height: 20px; fill: none; stroke: currentColor; stroke-width: 1.75; stroke-linecap: round; stroke-linejoin: round; }
.thq .i-sm { width: 16px; height: 16px; }

/* ── type ── */
.thq .label { display: block; font: 500 12px/1 var(--mono); letter-spacing: .14em; text-transform: uppercase; color: var(--ink-faint); }
.thq .h1 { font: 750 clamp(46px, 8vw, 112px)/.92 var(--sans); letter-spacing: -.055em; text-wrap: balance; }
.thq .h2 { font: 750 clamp(38px, 5.6vw, 80px)/.95 var(--sans); letter-spacing: -.05em; text-wrap: balance; }
.thq .h3 { font: 700 clamp(24px, 2.4vw, 30px)/1.1 var(--sans); letter-spacing: -.03em; }
.thq .o { color: var(--brass); }
.thq .lead { font-size: 18px; line-height: 1.6; color: var(--ink-soft); max-width: 560px; text-wrap: pretty; }
.thq p { text-wrap: pretty; }

/* ── buttons ── */
.thq .btn { display: inline-flex; align-items: center; justify-content: center; gap: 10px; min-height: 48px; padding: 0 22px; border-radius: 999px; border: 1.5px solid var(--ink); background: var(--ink); color: var(--ground); font: 600 15.5px/1 var(--sans); cursor: pointer; transition: transform .15s var(--ease), background .15s; white-space: nowrap; }
.thq .btn:hover { transform: translateY(-1px); }
.thq .btn.ghost { background: transparent; color: var(--ink); border-color: var(--line-2); }
.thq .btn.ghost:hover { border-color: var(--ink); }
.thq .btn.accent { background: var(--brass-ui); border-color: var(--brass-ui); color: var(--on-accent); }
.thq .btn.accent:hover { background: var(--brass-hi); border-color: var(--brass-hi); }
.thq .btn.sm { min-height: 44px; padding: 0 18px; font-size: 14.5px; }
.thq .btn .i { width: 17px; height: 17px; }

/* ── header ── */
.thq .hdr { position: sticky; top: 0; z-index: 50; background: color-mix(in srgb, var(--ground) 84%, transparent); backdrop-filter: blur(14px); -webkit-backdrop-filter: blur(14px); border-bottom: 1px solid transparent; transition: border-color .2s; }
.thq .hdr.scrolled { border-bottom-color: var(--line-2); }
/* The dark header is solid: see-through, it showed the white page beneath it
   as grey against the black hero. */
.thq .hdr.band { background: var(--ground); backdrop-filter: none; -webkit-backdrop-filter: none; }
/* The hero runs on under the dark header; the formats marquee closes it. */
.thq .hero.band { padding-bottom: 0; }
.thq .hero.band .marq { border-bottom: 0; }
.thq .hdr-in { display: flex; align-items: center; height: 72px; gap: 28px; }
.thq .lockup { display: inline-flex; align-items: center; min-height: 44px; flex: none; }
.thq .hnav { display: flex; align-items: center; gap: 2px; margin-right: auto; font: 500 15px/1 var(--sans); color: var(--ink-soft); }
.thq .hnav > a, .thq .dd > summary { display: inline-flex; align-items: center; gap: 6px; min-height: 44px; padding: 0 12px; border-radius: 10px; cursor: pointer; list-style: none; }
.thq .dd > summary::-webkit-details-marker { display: none; }
.thq .hnav > a:hover, .thq .dd > summary:hover, .thq .dd[open] > summary { background: var(--wash); color: var(--ink); }
.thq .dd { position: relative; }
.thq .dd .chev { width: 8px; height: 8px; border-right: 1.5px solid currentColor; border-bottom: 1.5px solid currentColor; transform: rotate(45deg) translateY(-2px); }
.thq .dd-panel { position: absolute; top: calc(100% + 10px); left: -12px; width: 600px; background: var(--card); border: 1px solid var(--line); border-radius: 18px; padding: 10px; display: grid; grid-template-columns: 1fr 1fr; gap: 2px; box-shadow: var(--shadow-xl); }
.thq .dd-panel a { display: grid; grid-template-columns: 40px 1fr; gap: 12px; padding: 12px; border-radius: 12px; }
.thq .dd-panel a:hover { background: var(--wash); }
.thq .dd-panel .n { width: 40px; height: 40px; border-radius: 10px; background: var(--wash-2); display: grid; place-items: center; font: 600 13px/1 var(--mono); color: var(--brass); }
.thq .dd-panel b { display: block; font: 600 15px/1.3 var(--sans); color: var(--ink); }
.thq .dd-panel span { font-size: 13.5px; line-height: 1.4; color: var(--ink-faint); }
.thq .hact { display: flex; align-items: center; gap: 14px; font: 500 15px/1 var(--sans); }
.thq .hact > a:not(.btn) { display: inline-flex; align-items: center; min-height: 44px; }
.thq .hact .play { color: var(--ink-faint); font-size: 14px; gap: 5px; }
.thq .hact .play u { color: var(--ink); text-decoration-color: var(--brass-ui); text-underline-offset: 3px; text-decoration-thickness: 1.5px; }
.thq .nav-menu { display: none; position: relative; }
.thq .nav-menu > summary { list-style: none; display: grid; place-items: center; width: 44px; height: 44px; border-radius: 12px; border: 1px solid var(--line-2); background: var(--card); color: var(--ink); cursor: pointer; }
.thq .nav-menu > summary::-webkit-details-marker { display: none; }
.thq .menu-panel { position: absolute; right: 0; top: calc(100% + 10px); width: min(300px, calc(100vw - 32px)); display: grid; padding: 8px; border-radius: 16px; border: 1px solid var(--line); background: var(--card); box-shadow: var(--shadow-xl); z-index: 60; }
.thq .menu-panel a { display: flex; align-items: center; min-height: 46px; padding: 0 14px; border-radius: 10px; font: 500 16px/1 var(--sans); color: var(--ink-soft); }
.thq .menu-panel a:hover { background: var(--wash); color: var(--ink); }
.thq .menu-panel hr { border: 0; border-top: 1px solid var(--line); margin: 6px 4px; }
@media (max-width: 1060px) { .thq .hnav, .thq .hact > a.play, .thq .hact > a.si { display: none; } .thq .nav-menu { display: block; } .thq .hdr-in { justify-content: space-between; } }
/* On a phone the lockup (at its brand size), a button and the menu do not fit
   with room to spare — 15px over on a 393px phone — and the lockup keeps its
   size: "Start free" moves to the top of the menu instead. */
@media (max-width: 440px) { .thq .hdr-in { gap: 8px; } .thq .hact { gap: 6px; } .thq .hact > .btn.sm { display: none; } }
.thq .menu-panel .menu-cta { display: none; }
@media (max-width: 440px) { .thq .menu-panel .menu-cta { display: flex; color: var(--brass); font-weight: 650; } }

/* ── hero ── */
.thq .hero { padding: 80px 0 0; overflow: hidden; }
.thq .hero .kicker { margin-bottom: 26px; }
.thq .hero-top { display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 360px); gap: 40px; align-items: end; }
.thq .hero-side { padding-bottom: 12px; display: grid; gap: 24px; }
.thq .hero-side p { color: var(--ink-soft); font-size: 18.5px; line-height: 1.55; }
.thq .ctas { display: flex; gap: 10px; flex-wrap: wrap; }
.thq .proof { display: flex; flex-wrap: wrap; gap: 8px 28px; margin-top: 44px; padding-top: 22px; border-top: 1px solid var(--line); font-size: 14.5px; color: var(--ink-soft); }
.thq .proof b { color: var(--ink); font-weight: 650; }
/* The laptop and the phone share one grid cell, so the stage is exactly as tall
   as what it holds: the laptop screen is shown WHOLE inside the page width (it
   once ran 200px off the right edge and 50px down over the line below it), and
   the phone stands in front of its left edge, dropping below it. */
.thq .stage { display: grid; margin-top: 64px; }
.thq .stage > * { grid-area: 1 / 1; }
.thq .stage .desk { margin-left: 20%; align-self: start; border-radius: 16px; overflow: hidden; box-shadow: var(--shadow-xl); }
.thq .stage .phone { position: relative; z-index: 1; align-self: start; width: min(300px, 26%); margin-top: 40px; }
.thq .real { margin-top: 24px; font-size: 14px; color: var(--ink-faint); }
.thq .real b { color: var(--ink-soft); font-weight: 600; }
@media (max-width: 1000px) { .thq .hero-top { grid-template-columns: minmax(0, 1fr); } .thq .stage { margin-top: 44px; } .thq .stage .desk { display: none; } .thq .stage .phone { width: min(300px, 78%); margin: 0 auto; } }
@media (max-width: 760px) { .thq .hero { padding-top: 48px; } .thq .proof { gap: 6px 18px; margin-top: 32px; } }

/* ── the phone: a physical object, dark on any ground ── */
.thq .phone { border-radius: 46px; padding: 9px; background: black; box-shadow: 0 40px 80px -34px rgba(0,0,0,.55), inset 0 0 0 1.5px rgba(255,255,255,.12); }
.thq .phone img { border-radius: 38px; width: 100%; }
.thq .phone.sm { border-radius: 32px; padding: 6px; }
.thq .phone.sm img { border-radius: 27px; }

/* ── formats marquee ── */
.thq .marq { margin-top: 80px; border-top: 1px solid var(--line); border-bottom: 1px solid var(--line); overflow: hidden; white-space: nowrap; padding: 22px 0; }
.thq .marq-track { display: inline-flex; gap: 44px; font: 700 clamp(30px, 4.4vw, 60px)/1.1 var(--sans); letter-spacing: -.04em; }
.thq .marq-track span:nth-child(odd) { color: var(--ink); }
.thq .marq-track span:nth-child(even) { color: var(--ink-faint); }
.thq .marq-track em { font-style: normal; color: var(--brass); }
.thq-js .marq-track { animation: thq-slide 70s linear infinite; }
@keyframes thq-slide { to { transform: translateX(-50%); } }

/* ── sections ── */
.thq .sec { padding: 140px 0; }
.thq .sec.tint { background: var(--ground-2); }
.thq .shead { display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 420px); gap: 40px; align-items: end; margin-bottom: 72px; }
.thq .shead .label { margin-bottom: 22px; }
.thq .shead > p, .thq .shead > div > p { color: var(--ink-soft); font-size: 18px; }
.thq .shead.center { grid-template-columns: 1fr; justify-items: center; text-align: center; }
@media (max-width: 900px) { .thq .sec { padding: 88px 0; } .thq .shead { grid-template-columns: minmax(0, 1fr); gap: 18px; margin-bottom: 44px; } }

/* ── the round: one Saturday, both sides ── */
.thq .round { display: grid; grid-template-columns: minmax(0, 1fr) 360px; gap: 96px; }
.thq .step { min-height: min(72vh, 620px); display: flex; flex-direction: column; justify-content: center; padding: 40px 0; border-top: 1px solid var(--line); }
.thq-js .step { opacity: .32; transition: opacity .35s; }
.thq-js .step.on { opacity: 1; }
.thq .step-t { display: flex; align-items: center; gap: 16px; }
.thq .step-t b { font: 600 60px/1 var(--mono); letter-spacing: -.05em; color: var(--brass); font-variant-numeric: tabular-nums; }
.thq .who { display: inline-flex; align-items: center; height: 26px; padding: 0 10px; border-radius: 999px; font: 600 11.5px/1 var(--mono); letter-spacing: .12em; text-transform: uppercase; }
.thq .who.org { background: var(--ink); color: var(--ground); }
.thq .who.pl { background: var(--accent-a12); color: var(--brass-hi); }
.thq .step h3 { margin: 22px 0 12px; max-width: 560px; }
.thq .step p { color: var(--ink-soft); max-width: 520px; }
.thq .step ul { margin-top: 18px; display: grid; gap: 8px; font-size: 15.5px; color: var(--ink-soft); }
.thq .step li { display: grid; grid-template-columns: 18px 1fr; }
.thq .step li::before { content: ""; width: 6px; height: 6px; border-radius: 50%; background: var(--brass-ui); margin-top: 10px; }
.thq .step .inl { display: none; }
.thq .pin { position: sticky; top: 108px; align-self: start; height: calc(100vh - 140px); max-height: 860px; display: grid; align-content: center; justify-items: center; gap: 18px; }
.thq .pin .phone { width: 320px; }
.thq .pin .scr { position: relative; aspect-ratio: 600 / 1298; border-radius: 38px; overflow: hidden; background: var(--ground-2); }
.thq .pin .scr img { position: absolute; inset: 0; border-radius: 0; opacity: 0; transition: opacity .45s ease; }
.thq .pin .scr img.on { opacity: 1; }
.thq .clock { display: flex; gap: 6px; }
.thq .clock i { width: 26px; height: 4px; border-radius: 2px; background: var(--line-2); transition: background .3s; }
.thq .clock i.on { background: var(--brass-ui); }
.thq .pin .cap { font: 500 12.5px/1.3 var(--mono); letter-spacing: .04em; color: var(--ink-faint); text-align: center; min-height: 17px; }
@media (max-width: 1000px) { .thq .round { grid-template-columns: minmax(0, 1fr); } .thq .pin { display: none; } .thq .step { min-height: 0; padding: 44px 0; } .thq-js .step { opacity: 1; } .thq .step .inl { display: block; width: min(300px, 80%); margin: 28px auto 0; } }

/* ── five reasons: the one orange band ── */
.thq .why { background: var(--brass-ui); color: var(--on-accent); padding: 140px 0; }
.thq .why .label { color: var(--on-accent); }
.thq .why .h2 { margin-top: 22px; max-width: 900px; }
.thq .why .lead { color: var(--on-accent); margin: 24px 0 72px; max-width: 580px; }
.thq .reasons { border-top: 2px solid var(--on-accent); }
.thq .reason { display: grid; grid-template-columns: 90px minmax(0, 1.1fr) minmax(0, 1fr); gap: 40px; padding: 32px 0; border-bottom: 1px solid color-mix(in srgb, var(--on-accent) 30%, transparent); align-items: baseline; }
.thq .reason .n { font: 600 20px/1 var(--mono); }
.thq .reason h3 { font: 750 clamp(26px, 3.2vw, 44px)/1.02 var(--sans); letter-spacing: -.04em; }
.thq .reason p { font-size: 17px; }
.thq .reason p b { font-weight: 650; }
@media (max-width: 900px) { .thq .why { padding: 88px 0; } .thq .reason { grid-template-columns: 44px minmax(0, 1fr); gap: 10px 14px; } .thq .reason p { grid-column: 2; } }

/* ── side by side: the usual way ── */
.thq .usual { border: 1px solid var(--line); border-radius: var(--r); overflow: hidden; background: var(--card); }
.thq .u-hd, .thq .u-row { display: grid; grid-template-columns: 130px minmax(0, 1fr) minmax(0, 1fr); gap: 0 28px; padding: 18px 30px; border-bottom: 1px solid var(--line); }
.thq .u-hd { padding-top: 22px; padding-bottom: 20px; }
.thq .u-hd b { font: 700 19px/1 var(--sans); letter-spacing: -.02em; }
.thq .u-hd b.now { color: var(--brass); }
.thq .u-row:last-child { border-bottom: 0; }
.thq .u-row i { font: 500 12px/1.5 var(--mono); letter-spacing: .08em; text-transform: uppercase; color: var(--ink-faint); font-style: normal; padding-top: 3px; }
.thq .u-row .before { color: var(--ink-faint); text-decoration: line-through; text-decoration-color: var(--line-2); }
.thq .u-row .after { color: var(--ink); font-weight: 550; }
.thq .usual .sr { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0 0 0 0); white-space: nowrap; }
@media (max-width: 900px) { .thq .u-hd { display: none; } .thq .u-row { grid-template-columns: minmax(0, 1fr); gap: 4px; padding: 16px 20px; } .thq .u-row .before { font-size: 14.5px; } .thq .u-row .after::before { content: "→ "; color: var(--brass); font-weight: 700; } }

/* ── side by side: the names you know ── */
.thq .vs { margin-top: 110px; }
.thq .seg { display: inline-flex; flex-wrap: wrap; gap: 4px; padding: 5px; border-radius: 999px; background: var(--wash-2); }
.thq .tab { position: relative; min-height: 42px; padding: 0 18px; border-radius: 999px; display: inline-flex; align-items: center; gap: 8px; font: 600 14.5px/1.2 var(--sans); color: var(--ink-soft); cursor: pointer; }
.thq .tab:hover { color: var(--ink); }
.thq .tab:has(input:checked) { background: var(--ink); color: var(--ground); }
.thq .tab:has(input:focus-visible) { outline: 2px solid var(--brass-ui); outline-offset: 2px; }
.thq .glance { display: grid; grid-template-columns: minmax(0, 1fr); gap: 16px; margin-top: 18px; }
.thq .glance-col { padding: 26px 28px; border-radius: var(--r); background: var(--card); border: 1px solid var(--line); }
.thq .glance-col.further { background: transparent; }
.thq .glance-col h3 { font: 700 18px/1.2 var(--sans); margin-bottom: 14px; }
.thq .glance-col ul { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 10px 32px; }
.thq .glance-col li { display: grid; grid-template-columns: 22px minmax(0, 1fr); gap: 8px; font-size: 15px; color: var(--ink-soft); }
.thq .glance-col li .i { width: 17px; height: 17px; color: var(--flag); margin-top: 3px; stroke-width: 2.2; }
.thq .glance-col li .dot { width: 7px; height: 7px; border-radius: 50%; background: var(--ink-faint); margin: 9px 0 0 5px; }
.thq .vs-legal { margin-top: 20px; font-size: 13px; line-height: 1.55; color: var(--ink-faint); max-width: 900px; }
@media (max-width: 900px) { .thq .glance { grid-template-columns: minmax(0, 1fr); } .thq .vs { margin-top: 72px; } }

/* ── side by side: TourneyHQ and five you know (2026-09-29) ──
   One table, a column per company, a mark and a few words per cell, in the
   "scoreboard" colours Ajay chose: a black header, TourneyHQ's column framed in
   orange, solid marks. On a phone the feature names and TourneyHQ stay pinned
   and the five rivals slide past two at a time, inside the table's own
   scroller — the page itself never scrolls sideways. */
.thq .cx-cue { display: none; }
/* position: relative makes the scroller the containing block of the screen-reader-only
   labels (.sr, absolutely positioned) in its cells. Without it they escaped the
   overflow to the page, and phones widened the layout viewport to 621px and zoomed out. */
.thq .cx-scroll { position: relative; overflow-x: auto; border: 1px solid var(--ink); border-radius: 18px; background: var(--card); overscroll-behavior-x: contain; scroll-snap-type: x proximity; -webkit-overflow-scrolling: touch; }
.thq .cx-scroll:focus-visible { outline: 2px solid var(--brass-ui); outline-offset: 3px; }
.thq .cx { width: 100%; min-width: 1120px; border-collapse: separate; border-spacing: 0; table-layout: fixed; }
.thq .cx th, .thq .cx td { padding: 14px 10px; border-top: 1px solid var(--line); text-align: center; vertical-align: middle; background: var(--card); }
.thq .cx thead th { border-top: 0; padding: 18px 10px 16px; background: var(--ink); color: var(--ground); scroll-snap-align: start; vertical-align: bottom; }
.thq .cx thead th b { display: block; font: 700 15px/1.2 var(--sans); letter-spacing: -.01em; }
.thq .cx thead th span:not(.sr) { display: block; margin-top: 5px; font: 500 10.5px/1.2 var(--mono); letter-spacing: .08em; text-transform: uppercase; opacity: .72; }
.thq .cx .cx-lab { width: 232px; text-align: left; padding-left: 20px; position: sticky; left: 0; z-index: 2; font: 650 14.5px/1.3 var(--sans); color: var(--ink); }
.thq .cx .cx-lab small { display: block; margin-top: 4px; font: 400 12.5px/1.4 var(--sans); color: var(--ink-faint); }
.thq .cx thead .cx-lab { background: var(--ink); }
.thq .cx .cx-us { position: sticky; left: 232px; z-index: 2; width: 150px; background: color-mix(in srgb, var(--brass-ui) 5%, var(--card)); box-shadow: inset 2px 0 0 var(--brass-ui), inset -2px 0 0 var(--brass-ui); }
.thq .cx thead .cx-us { background: var(--brass-ui); color: var(--on-accent); box-shadow: none; }
/* Faded to .72 like the others, the plan names fell to 3.6:1 on the orange. */
.thq .cx thead .cx-us span:not(.sr) { opacity: 1; }
/* One line on a laptop: wrapped, "Par · Birdie ·" left "Eagle" alone underneath. */
@media (min-width: 761px) { .thq .cx thead .cx-us span:not(.sr) { letter-spacing: .03em; white-space: nowrap; } }
.thq .cx tbody tr:last-child .cx-us { box-shadow: inset 2px 0 0 var(--brass-ui), inset -2px 0 0 var(--brass-ui), inset 0 -2px 0 var(--brass-ui); }
.thq .cx td { font-size: 14px; color: var(--ink-soft); }
.thq .cx td b { display: block; font: 750 15px/1.25 var(--sans); letter-spacing: -.01em; color: var(--ink); }
.thq .cx td small { display: block; margin-top: 5px; font-size: 11.5px; line-height: 1.3; color: var(--ink-soft); }
.thq .cx-m { display: inline-grid; place-items: center; width: 24px; height: 24px; border-radius: 50%; font: 700 13px/1 var(--sans); vertical-align: middle; }
.thq .cx-yes { background: var(--flag); color: var(--card); }
.thq .cx-part { background: var(--warn); color: var(--card); }
.thq .cx-no { color: var(--danger); box-shadow: inset 0 0 0 1.6px var(--danger); }
.thq .cx-na { width: auto; font-weight: 400; color: var(--ink-faint); }
.thq .cx .cx-src th, .thq .cx .cx-src td { font: 500 11.5px/1.35 var(--mono); color: var(--ink-faint); overflow-wrap: anywhere; }
.thq .cx .cx-src a { color: var(--ink-soft); text-decoration: underline; text-underline-offset: 2px; }
.thq .cx .cx-src a:hover { color: var(--brass); }
.thq .cx-key { display: flex; flex-wrap: wrap; gap: 8px 20px; margin: 14px 2px 0; font-size: 13px; color: var(--ink-faint); }
.thq .cx-key > span { display: inline-flex; align-items: center; gap: 7px; }
.thq .cx-key .cx-m { width: 18px; height: 18px; font-size: 10px; }
@media (max-width: 760px) {
  .thq .cx-cue { display: flex; align-items: center; gap: 6px; margin: 0 0 10px; font: 650 12px/1 var(--mono); letter-spacing: .08em; text-transform: uppercase; color: var(--brass); }
  .thq .cx-cue .i { width: 14px; height: 14px; }
  .thq .cx-scroll { margin: 0 calc(-1 * max(20px, env(safe-area-inset-right))) 0 calc(-1 * max(20px, env(safe-area-inset-left))); border-radius: 0; border-left: 0; border-right: 0; scroll-snap-type: x mandatory; scroll-padding-left: 214px; }
  .thq .cx { min-width: calc(118px + 96px + 5 * 88px); }
  .thq .cx th, .thq .cx td { padding: 11px 5px; }
  .thq .cx thead th { padding: 14px 4px 12px; }
  .thq .cx thead th b { font-size: 12.5px; }
  .thq .cx thead th span:not(.sr) { font-size: 8.5px; letter-spacing: .04em; }
  .thq .cx .cx-lab { width: 118px; padding-left: 14px; font-size: 12.5px; }
  .thq .cx .cx-lab small { font-size: 10.5px; }
  .thq .cx .cx-us { left: 118px; width: 96px; }
  .thq .cx td { font-size: 12.5px; }
  .thq .cx td b { font-size: 12.5px; }
  .thq .cx td small { font-size: 10px; }
  .thq .cx-m { width: 22px; height: 22px; font-size: 12px; }
}

/* ── pricing: what changes from one plan to the next ── */
.thq .tier-how { margin: 8px 0 0; font-size: 12.5px; line-height: 1.4; color: var(--ink-faint); }
/* Narrow plan cards: the note below the cards says the same once, so each card drops it. */
@media (max-width: 700px) { .thq .tier-how { display: none; } }
/* The billing switch on the smallest phones: one row, not a stacked pill. */
@media (max-width: 400px) { .thq .seg.bill { flex-wrap: nowrap; } .thq .seg.bill .tab { padding: 0 12px; font-size: 13.5px; } .thq .seg.bill em { font-size: 9.5px; padding: 3px 5px; } }
.thq .tier.hot .tier-how { color: color-mix(in srgb, var(--ground) 70%, transparent); }
.thq .cp { margin-top: 28px; }
.thq .cp h3 { font: 750 22px/1.2 var(--sans); letter-spacing: -.02em; }
.thq .cp-sub { color: var(--ink-soft); font-size: 15px; margin: 4px 0 16px; }
.thq .cp-t { width: 100%; border-collapse: separate; border-spacing: 0; table-layout: fixed; background: var(--card); border: 1px solid var(--line); border-radius: 18px; overflow: hidden; }
.thq .cp-t td { hyphens: auto; }
.thq .cp-t th, .thq .cp-t td { overflow-wrap: break-word; padding: 14px 12px; border-top: 1px solid var(--line); text-align: center; vertical-align: middle; font-size: 14.5px; color: var(--ink); }
.thq .cp-t thead th { border-top: 0; padding: 18px 12px; font: 750 16px/1.2 var(--sans); background: var(--ink); color: var(--ground); }
.thq .cp-t thead th:first-child { width: 34%; }
.thq .cp-t thead th.hot { background: var(--brass-ui); color: var(--on-accent); }
.thq .cp-t td.hot { background: color-mix(in srgb, var(--brass-ui) 5%, var(--card)); }
.thq .cp-t tbody th { text-align: left; padding-left: 20px; font: 600 14.5px/1.35 var(--sans); }
.thq .cp-t td b { display: block; font: 800 18px/1.15 var(--sans); letter-spacing: -.02em; }
.thq .cp-t td small { display: block; font-size: 12px; color: var(--ink-faint); margin-top: 4px; }
.thq .cp-m { display: inline-grid; place-items: center; width: 24px; height: 24px; border-radius: 50%; font: 700 13px/1 var(--sans); }
.thq .cp-y { background: var(--flag); color: var(--card); }
.thq .cp-x { color: var(--danger); box-shadow: inset 0 0 0 1.6px var(--danger); }
.thq .cp-t tfoot td { hyphens: manual; border-top: 1px solid var(--line-2); padding: 18px 20px; text-align: left; font-size: 15px; color: var(--ink-soft); background: var(--ground-2); }
.thq .cp-t tfoot b { color: var(--ink); }
.thq .cp-t tfoot a { display: inline-flex; align-items: center; gap: 6px; color: var(--brass); font-weight: 650; white-space: nowrap; min-height: 44px; }
.thq .cp-t tfoot a .i { width: 15px; height: 15px; }
@media (max-width: 760px) {
  .thq .cp-t th, .thq .cp-t td { padding: 11px 5px; font-size: 12.5px; }
  .thq .cp-t thead th { font-size: 13.5px; padding: 14px 4px; }
  .thq .cp-t thead th:first-child { width: 34%; }
  .thq .cp-t tbody th { padding-left: 12px; font-size: 12px; hyphens: auto; }
  .thq .cp-t td b { font-size: 14px; }
  .thq .cp-t td small { font-size: 10.5px; }
  .thq .cp-t tfoot td { font-size: 14px; padding: 14px; }
}

/* ── the showcase: the real app, by tab ── */
.thq .show { display: grid; grid-template-columns: 240px minmax(0, 1fr); gap: 14px; padding: 14px; border-radius: 26px; background: var(--card); border: 1px solid var(--line); }
/* position: relative on every horizontal scroller: its .sr inputs are absolutely
   positioned, and without a containing block inside the scroller they escape it and
   widen the page on phones (the #723 bug, again here). */
.thq .show-rail, .thq .steps { position: relative; }
.thq .show-rail { display: grid; gap: 2px; align-content: start; padding: 8px; }
.thq .show-rail .label { margin: 14px 10px 8px; }
.thq .show-rail .label:first-child { margin-top: 6px; }
.thq .show-tab { display: grid; gap: 3px; padding: 12px 14px; border-radius: 12px; cursor: pointer; }
.thq .show-tab b { font: 600 15.5px/1.3 var(--sans); color: var(--ink-soft); }
.thq .show-tab span { font-size: 13px; line-height: 1.35; color: var(--ink-faint); }
.thq .show-tab:hover b { color: var(--ink); }
.thq .show-tab:has(input:checked) { background: var(--ink); }
.thq .show-tab:has(input:checked) b { color: var(--ground); }
.thq .show-tab:has(input:checked) span { color: color-mix(in srgb, var(--ground) 72%, var(--ink)); }
.thq .show-tab:has(input:focus-visible) { outline: 2px solid var(--brass-ui); outline-offset: 2px; }
/* The stage (2026-09-29): a dark stage lit in the brand's orange, the real
   screen upright in a phone, and numbered pins beside it — level with what each
   note describes. Hovering a note lights its pin. The capture itself is never
   drawn on. UPRIGHT and STILL on purpose: a 3D-rotated or floating image is
   resampled every frame and its text goes soft (Ajay: "can't you see the
   blurriness"); the depth comes from light and shadow, never from transforms. */
/* The showcase is painted dark on the light page, so the orange its pins and
   numbers use is the dark palette's (rust on black read at 2.5:1, black on rust at 3:1). */
.thq .show-view { --brass-hi: var(--paper-accent); position: relative; border-radius: 20px; min-height: 700px; display: grid; place-items: center; overflow: hidden; padding: 48px 40px;
  background: radial-gradient(70% 70% at 28% 30%, color-mix(in srgb, var(--brass-ui) 26%, var(--ink)) 0%, var(--ink) 72%); }
.thq .show-f { display: none; grid-template-columns: auto minmax(0, 1fr); align-items: center; gap: 56px; width: 100%; max-width: 820px; }
.thq .stage-phone { position: relative; width: 290px; justify-self: center; }
.thq .stage-phone .phone { box-shadow: 0 50px 90px -24px rgba(0,0,0,.85), 0 20px 50px -18px color-mix(in srgb, var(--brass-ui) 55%, transparent), inset 0 0 0 1.5px rgba(255,255,255,.14); }
.thq .stage-pins { position: absolute; top: 9px; bottom: 9px; right: -26px; width: 0; margin: 0; padding: 0; list-style: none; }
.thq .stage-pins li { position: absolute; right: -14px; transform: translateY(-50%); width: 30px; height: 30px; border-radius: 50%; display: grid; place-items: center;
  font: 800 13px/1 var(--sans); color: var(--ink); background: var(--brass-hi); box-shadow: 0 0 0 5px color-mix(in srgb, var(--brass-hi) 22%, transparent); transition: transform .2s, box-shadow .2s; }
.thq .stage-pins li::before { content: ""; position: absolute; right: 100%; top: 50%; width: 16px; height: 1.5px; background: color-mix(in srgb, var(--brass-hi) 70%, transparent); }
.thq .stage-notes { color: color-mix(in srgb, var(--ground) 70%, transparent); }
.thq .stage-notes ol { list-style: none; margin: 0; padding: 0; display: grid; gap: 22px; counter-reset: note; }
.thq .stage-notes li { counter-increment: note; position: relative; padding-left: 54px; font-size: 15.5px; line-height: 1.5; cursor: default; }
.thq .stage-notes li::before { content: counter(note); position: absolute; left: 0; top: 0; width: 36px; height: 36px; border-radius: 50%; display: grid; place-items: center;
  font: 800 15px/1 var(--sans); color: var(--brass-hi); box-shadow: inset 0 0 0 1.5px color-mix(in srgb, var(--brass-hi) 60%, transparent); transition: background .2s, color .2s; }
.thq .stage-notes b { display: block; color: var(--ground); font: 750 19px/1.25 var(--sans); letter-spacing: -.015em; margin-bottom: 3px; }
.thq .stage-notes li:hover::before { background: var(--brass-hi); color: var(--ink); }
.thq .show-f:has(.stage-notes li:nth-child(1):hover) .stage-pins li:nth-child(1),
.thq .show-f:has(.stage-notes li:nth-child(2):hover) .stage-pins li:nth-child(2),
.thq .show-f:has(.stage-notes li:nth-child(3):hover) .stage-pins li:nth-child(3) { transform: translateY(-50%) scale(1.25); box-shadow: 0 0 0 9px color-mix(in srgb, var(--brass-hi) 30%, transparent); }

__SHOW_FRAMES__
@media (max-width: 1000px) {
  .thq .show { grid-template-columns: minmax(0, 1fr); padding: 10px; }
  .thq .show-rail { grid-auto-flow: column; grid-auto-columns: max-content; overflow-x: auto; scrollbar-width: none; padding: 4px; }
  .thq .show-rail .label { display: none; }
  .thq .show-tab span { display: none; }
  .thq .show-tab { border: 1px solid var(--line); border-radius: 999px; padding: 0 16px; min-height: 44px; align-content: center; }
  .thq .show-view { min-height: 0; padding: 36px 20px 30px; }
  .thq .show-f { grid-template-columns: minmax(0, 1fr); gap: 34px; }
  .thq .stage-phone { width: min(236px, 62vw); }
  .thq .stage-pins { right: -20px; } .thq .stage-pins li { width: 26px; height: 26px; font-size: 12px; right: -12px; }
  .thq .stage-notes li { padding-left: 48px; font-size: 14.5px; } .thq .stage-notes li::before { width: 32px; height: 32px; font-size: 13.5px; }
  .thq .stage-notes b { font-size: 17px; }
}

/* ── formats: three real boards ── */
.thq .boards { display: grid; grid-template-columns: repeat(3, minmax(0, 260px)); justify-content: center; gap: 48px; margin-top: 64px; }
/* Packed to the top: stretched to the tallest caption, a figure handed the spare
   height to its phone, and two of the three bezels grew a thick black chin. */
.thq .boards figure { display: grid; gap: 16px; align-content: start; }
.thq .boards figcaption { text-align: center; display: grid; gap: 4px; }
.thq .boards figcaption b { font: 650 15.5px/1.3 var(--sans); }
.thq .boards figcaption span { font-size: 14px; color: var(--ink-soft); text-wrap: balance; }
@media (max-width: 900px) {
  .thq .boards { display: flex; justify-content: flex-start; gap: 16px; overflow-x: auto; scroll-snap-type: x mandatory; scroll-padding-inline: 20px; margin: 44px -20px 0; padding: 4px 20px 8px; scrollbar-width: none; }
  .thq .boards figure { flex: 0 0 min(74%, 280px); scroll-snap-align: start; }
}

/* ── every feature ── */
.thq .fx { margin-top: 110px; }
.thq .fx-bar { display: flex; flex-wrap: wrap; align-items: center; gap: 8px; margin-bottom: 22px; }
.thq .fx-bar .chip { min-height: 42px; padding: 0 16px; border-radius: 999px; border: 1px solid var(--line-2); background: var(--card); display: inline-flex; align-items: center; gap: 6px; font: 600 14px/1 var(--sans); color: var(--ink-soft); cursor: pointer; }
.thq .fx-bar .chip i { font: 500 12px/1 var(--mono); font-style: normal; color: var(--ink-faint); }
.thq .fx-bar .chip:has(input:checked) i { color: inherit; opacity: .72; }
.thq .fx-bar .chip:has(input:checked) { background: var(--ink); color: var(--ground); border-color: var(--ink); }
.thq .fx-bar .chip:has(input:focus-visible) { outline: 2px solid var(--brass-ui); outline-offset: 2px; }
.thq .fx-search { margin-left: auto; position: relative; }
.thq .fx-search input { height: 44px; width: 280px; border-radius: 999px; border: 1px solid var(--line-2); background: var(--card); padding: 0 18px; font: 400 15px/1 var(--sans); color: var(--ink); }
.thq .fx-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 1px; background: var(--line); border: 1px solid var(--line); border-radius: 18px; overflow: hidden; }
.thq .fx-grid .f { background: var(--card); padding: 20px 20px 22px; min-height: 116px; }
.thq .fx-grid .f small { display: block; font: 500 11px/1 var(--mono); letter-spacing: .1em; text-transform: uppercase; color: var(--brass); margin-bottom: 10px; }
.thq .fx-grid .f b { display: block; font: 600 15.5px/1.3 var(--sans); }
.thq .fx-grid .f span { display: block; font-size: 13.5px; line-height: 1.45; color: var(--ink-faint); margin-top: 5px; }
.thq .fx:has(input[name="fx"][value="top"]:checked) .f:not(.top) { display: none; }
.thq .fx:has(input[name="fx"][value="competition"]:checked) .f:not([data-g="competition"]),
.thq .fx:has(input[name="fx"][value="day"]:checked) .f:not([data-g="day"]),
.thq .fx:has(input[name="fx"][value="player"]:checked) .f:not([data-g="player"]),
.thq .fx:has(input[name="fx"][value="money"]:checked) .f:not([data-g="money"]) { display: none; }
.thq .fx.searching .f { display: block !important; }
.thq .fx.searching .f[hidden] { display: none !important; }
.thq .fx-none { display: none; padding: 30px; text-align: center; color: var(--ink-soft); }
.thq .fx.empty .fx-none { display: block; }
@media (max-width: 1000px) { .thq .fx-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); } .thq .fx-search { margin-left: 0; width: 100%; } .thq .fx-search input { width: 100%; } }
@media (max-width: 480px) { .thq .fx-grid { grid-template-columns: minmax(0, 1fr); } .thq .fx-grid .f { min-height: 0; } }

/* ── the money (a dark band) ── */
.thq .money-cols { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
.thq .mcard { background: var(--card); border-radius: 24px; padding: 34px; border: 1px solid var(--line); display: flex; flex-direction: column; }
.thq .mcard p { color: var(--ink-soft); margin-top: 10px; font-size: 16px; }
.thq .chips { display: flex; flex-wrap: wrap; gap: 8px; margin: 20px 0 26px; }
.thq .chips span { font: 500 13.5px/1 var(--sans); padding: 9px 12px; border-radius: 999px; border: 1px solid var(--line-2); color: var(--ink-soft); }
.thq .mcard .well { margin-top: auto; border-radius: 14px; overflow: hidden; }
/* A phone-width capture is never drawn wider than a phone shows it (1170px at 2x = 585): on
   an iPad the money cards stack to one column and the prizes card stretched to 680px, 1.72x. */
.thq .mcard .well:has(img[src*="prizes-org-phone"]) { width: min(100%, 440px); margin-left: auto; margin-right: auto; }
/* The trip money as the member sees it: the whole phone, not a slice of the list. */
.thq .mcard .money-phone { width: min(300px, 82%); margin: auto auto 0; }
@media (max-width: 900px) { .thq .money-cols { grid-template-columns: minmax(0, 1fr); } .thq .mcard { padding: 24px; } }

/* ── make it yours: the drag-to-compare slider ── */
.thq .yours { display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 1fr); gap: 80px; align-items: center; }
.thq .yours .facts { display: grid; gap: 22px; margin-top: 36px; }
.thq .yours .facts > div { display: grid; grid-template-columns: 44px minmax(0, 1fr); gap: 14px; }
.thq .yours .facts .ic { width: 44px; height: 44px; border-radius: 12px; background: var(--wash-2); display: grid; place-items: center; color: var(--brass); }
.thq .yours .facts h4 { font: 650 16.5px/1.3 var(--sans); }
.thq .yours .facts p { color: var(--ink-soft); font-size: 15.5px; margin-top: 2px; }
.thq .compare { display: grid; justify-items: center; gap: 16px; }
.thq .cmp-tabs { display: none; }
.thq .compare:has(input[name="cmp-mode"][value="ap"]:checked) .cmp-tabs[data-set="ap"],
.thq .compare:has(input[name="cmp-mode"][value="col"]:checked) .cmp-tabs[data-set="col"] { display: inline-flex; }
@media (max-width: 480px) { .thq .cmp-tabs { flex-wrap: nowrap; max-width: 100%; overflow-x: auto; scrollbar-width: none; } .thq .cmp-tabs .tab { flex: none; padding: 0 12px; font-size: 13.5px; } }
.thq .cmp-f { display: none; justify-items: center; gap: 16px; width: 100%; }
__CMP_FRAMES__
.thq .cmp-frame.phone { width: min(320px, 78vw); }
.thq .cmp-frame.phone .cmp-view { border-radius: 38px; }
.thq .cmp-frame.window { width: 100%; border-radius: 14px; overflow: hidden; box-shadow: var(--shadow-xl); }
.thq .cmp-view { position: relative; overflow: hidden; --pos: 50%; touch-action: pan-y; }
.thq .cmp-view img { display: block; width: 100%; height: auto; user-select: none; -webkit-user-drag: none; border-radius: 0; }
.thq .cmp-view .cmp-b { position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover; clip-path: inset(0 0 0 var(--pos)); }
.thq .cmp-line { position: absolute; top: 0; bottom: 0; left: var(--pos); width: 2px; margin-left: -1px; background: var(--brass-ui); pointer-events: none; }
.thq .cmp-line i { position: absolute; top: 50%; left: 50%; width: 38px; height: 38px; margin: -19px 0 0 -19px; border-radius: 50%; background: var(--brass-ui); box-shadow: 0 4px 14px rgba(0,0,0,.4); }
.thq .cmp-line i::before, .thq .cmp-line i::after { content: ""; position: absolute; top: 50%; width: 0; height: 0; border: 5px solid transparent; margin-top: -5px; }
.thq .cmp-line i::before { left: 6px; border-right-color: var(--on-accent); }
.thq .cmp-line i::after { right: 6px; border-left-color: var(--on-accent); }
.thq .cmp-range { position: absolute; inset: 0; width: 100%; height: 100%; margin: 0; opacity: 0; cursor: ew-resize; touch-action: pan-y; }
.thq .cmp-view:focus-within .cmp-line i { outline: 2px solid var(--ink); outline-offset: 2px; }
.thq .cmp-legend { display: flex; align-items: center; gap: 14px; font: 600 13.5px/1.3 var(--sans); color: var(--ink-soft); }
.thq .cmp-legend span { display: inline-flex; align-items: center; gap: 6px; }
.thq .cmp-legend .i { width: 15px; height: 15px; }
.thq .cmp-hint { font: 500 12px/1 var(--mono); color: var(--ink-faint); }
@media (max-width: 900px) { .thq .yours { grid-template-columns: minmax(0, 1fr); gap: 44px; } }

/* ── pricing ── */
.thq .per-y { display: none; }
.thq #pricing:has(input[name="bill"][value="y"]:checked) .per-y { display: inline; }
.thq #pricing:has(input[name="bill"][value="y"]:checked) .per-m { display: none; }
.thq .bill em { font-style: normal; font: 600 11px/1 var(--mono); color: var(--card); background: var(--flag); padding: 4px 7px; border-radius: 6px; }
.thq .ed-note { font-size: 14px; color: var(--ink-faint); display: flex; flex-wrap: wrap; gap: 6px 10px; align-items: center; margin-top: 14px; }
.thq .ed-note button { min-height: 44px; padding: 0 14px; border-radius: 999px; border: 1px solid var(--line-2); background: transparent; color: var(--ink); font: 600 13.5px/1 var(--sans); cursor: pointer; }
.thq .ed-note button:hover { border-color: var(--ink); }
.thq .tiers { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 18px; margin-top: 34px; }
.thq .tier { border-radius: 24px; padding: 34px; background: var(--card); border: 1px solid var(--line); display: grid; grid-template-rows: auto auto auto auto auto 1fr auto; gap: 16px; }
.thq .tier.hot { background: var(--ink); color: var(--ground); border-color: var(--ink); }
.thq .tier h3 { display: flex; justify-content: space-between; align-items: center; font: 700 20px/1 var(--sans); }
.thq .tier .badge { font: 500 11px/1 var(--mono); letter-spacing: .12em; text-transform: uppercase; background: var(--brass-ui); color: var(--on-accent); padding: 6px 8px; border-radius: 6px; }
.thq .tier .for { color: var(--ink-soft); font-size: 15px; min-height: 48px; }
.thq .tier.hot .for, .thq .tier.hot .price > span, .thq .tier.hot .price-sub, .thq .tier.hot .note { color: color-mix(in srgb, var(--ground) 70%, var(--ink)); }
.thq .price { display: flex; align-items: baseline; gap: 6px; }
.thq .price b { font: 750 60px/1 var(--sans); letter-spacing: -.05em; }
.thq .price > span { color: var(--ink-faint); font-size: 15px; }
.thq .price-sub { font-size: 13.5px; color: var(--ink-faint); margin-top: -8px; min-height: 20px; }
.thq .tier ul { display: grid; gap: 11px; align-content: start; padding-top: 18px; border-top: 1px solid var(--line); font-size: 15px; }
.thq .tier.hot ul { border-top-color: color-mix(in srgb, var(--ground) 18%, transparent); }
.thq .tier li { display: grid; grid-template-columns: 22px minmax(0, 1fr); gap: 6px; }
.thq .tier li .i { width: 17px; height: 17px; color: var(--brass); margin-top: 3px; stroke-width: 2.3; }
.thq .tier.hot li .i { color: var(--ground); }
.thq .tier .note { font-size: 12.5px; color: var(--ink-faint); line-height: 1.5; }
.thq .tier .btn { width: 100%; }
.thq .tier .btn .short { display: none; }
.thq .tier.hot .btn { background: var(--brass-ui); border-color: var(--brass-ui); color: var(--on-accent); }
.thq .tier-note { margin-top: 16px; font-size: 14px; color: var(--ink-faint); }
.thq .ultimate { display: grid; grid-template-columns: auto minmax(0, 1fr) auto; gap: 18px; align-items: center; margin-top: 18px; padding: 24px 28px; border-radius: 20px; border: 1px solid var(--line); }
.thq .ultimate .ic { width: 44px; height: 44px; border-radius: 12px; background: var(--wash-2); display: grid; place-items: center; color: var(--brass); }
.thq .ultimate h3 { font: 650 17px/1.3 var(--sans); }
.thq .ultimate p { font-size: 15px; color: var(--ink-soft); }
.thq .metered { margin-top: 18px; font-size: 13.5px; color: var(--ink-faint); max-width: 820px; }
@media (max-width: 1000px) { .thq .tiers { gap: 10px; } .thq .tier { padding: 24px 18px; } .thq .price b { font-size: 42px; } .thq .tier .btn .long { display: none; } .thq .tier .btn .short { display: inline; } }
@media (max-width: 700px) {
  .thq .tiers { gap: 8px; }
  .thq .tier { padding: 16px 8px 14px; gap: 10px; grid-template-rows: none; align-content: start; justify-items: center; text-align: center; border-radius: 16px; }
  .thq .tier .for, .thq .tier ul, .thq .tier .note, .thq .tier .price-sub { display: none; }
  .thq .tier h3 { flex-direction: column-reverse; gap: 6px; font-size: 15px; }
  /* Three narrow cards on a phone: the tagline badge wrapped to two cramped lines. */
  .thq .tier .badge { display: none; }
  .thq .tier:not(.hot) h3::after { content: ""; height: 17.5px; }
  .thq .price { flex-direction: column; align-items: center; gap: 2px; }
  .thq .price b { font-size: clamp(22px, 7vw, 30px); }
  .thq .price > span { font-size: 12px; }
  .thq .tier .btn { min-height: 44px; padding: 0 6px; font-size: 13px; }
  .thq .tier .btn .long { display: none; }
  .thq .tier .btn .short { display: inline; }
  .thq .ultimate { grid-template-columns: minmax(0, 1fr); }
  .thq .ultimate .ic { display: none; }
}
@media (max-width: 360px) { .thq .tier { padding: 14px 6px 12px; } .thq .tier .btn { font-size: 12px; } }

/* ── questions ── */
.thq .faq-split { display: grid; grid-template-columns: minmax(0, .8fr) minmax(0, 1.2fr); gap: 64px; }
.thq .faq-split .h2 { font-size: clamp(36px, 4.4vw, 60px); margin-top: 22px; }
.thq .faq-split .lead { margin: 18px 0 26px; }
.thq details.q { border-top: 1px solid var(--line); scroll-margin-top: 150px; }
.thq details.q:last-of-type { border-bottom: 1px solid var(--line); }
.thq details.q > summary { list-style: none; cursor: pointer; display: flex; justify-content: space-between; align-items: center; gap: 20px; min-height: 64px; padding: 16px 0; font: 650 18.5px/1.35 var(--sans); letter-spacing: -.01em; }
.thq details.q > summary::-webkit-details-marker { display: none; }
.thq details.q .pm { flex: none; width: 32px; height: 32px; border-radius: 50%; border: 1px solid var(--line-2); display: grid; place-items: center; font: 400 20px/1 var(--sans); color: var(--ink-soft); transition: transform .2s; }
.thq details.q[open] .pm { transform: rotate(45deg); }
.thq details.q .ans { padding: 0 44px 22px 0; color: var(--ink-soft); display: grid; gap: 12px; }
.thq details.q .ans a { color: var(--brass); text-decoration: underline; text-underline-offset: 3px; }
.thq details.q .ans ul { list-style: disc; padding-left: 20px; display: grid; gap: 6px; }
@media (max-width: 900px) { .thq .faq-split { grid-template-columns: minmax(0, 1fr); gap: 24px; } .thq details.q .ans { padding-right: 0; } }

/* ── the close ── */
.thq .close { padding: 140px 0; text-align: center; }
.thq .close .h1 { font-size: clamp(46px, 7.6vw, 112px); margin-top: 22px; }
.thq .close .lead { margin: 24px auto 40px; }
.thq .anchor { display: block; position: relative; top: -96px; visibility: hidden; }
.thq .authpanel {
  /* The sign-in form is the app's own component (LoginPanel), drawn with the
     app's --color-* tokens and carrying its own card. On the front door its
     controls wear the page's orange like every other control here, so those
     tokens are re-pointed for this panel only — never in globals.css. */
  --color-accent: var(--brass-ui); --color-accent-300: var(--brass-hi); --color-accent-400: var(--brass-hi); --color-accent-600: var(--brass);
  --color-accent-2: var(--brass); --color-accent-2-300: var(--brass-hi); --color-on-accent: var(--on-accent);
  --color-text: var(--ink); --color-surface: var(--ground-2);
  /* The helper lines ("At least 10 characters", what each kind of organizer
     gets) are .text-muted, which the app sets for its own dark ground: left
     alone it painted the app's pale dark-mode grey on this white card, and read as blank. */
  --color-text-muted: var(--ink-soft);
  /* The same for a sign-in error (TourneyHQv2 measured 3.38:1, and a near-black
     error box): the page's own danger, solved to text contrast, on a light wash. */
  --color-danger: var(--danger); --color-danger-bg: color-mix(in srgb, var(--danger) 9%, var(--card));
  width: min(460px, 100%); margin: 0 auto; text-align: left;
}
.thq .store-block { display: grid; gap: 12px; margin-top: 36px; justify-items: center; }
.thq .stores { display: flex; flex-wrap: wrap; gap: 10px; justify-content: center; }
.thq .store { display: inline-flex; align-items: center; gap: 11px; min-height: 52px; padding: 0 18px 0 14px; border-radius: 12px; background: black; color: white; text-align: left; border: 1px solid rgba(255,255,255,.2); }
.thq .store .i { width: 24px; height: 24px; stroke-width: 1.6; }
.thq .store > span { display: grid; gap: 3px; }
.thq .store small { font: 500 11px/1 var(--sans); color: rgba(255,255,255,.72); }
.thq .store b { font: 600 17px/1 var(--sans); letter-spacing: -.02em; }
.thq a.store.soon { opacity: .88; }
.thq .stores-note { font-size: 14px; color: var(--ink-faint); max-width: 460px; }

/* ── footer (a dark band) ── */
/* The footer (2026-09-29, "too much"): the mark, the links a visitor looks for
   at the bottom of a page, and one line of small print. The section links are in
   the header's Product menu; the footer no longer repeats them. */
.thq .ftr { padding: 48px 0 calc(28px + env(safe-area-inset-bottom)); }
.thq .ftr-row { display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: 18px 36px; }
.thq .ftr-row nav ul { display: flex; flex-wrap: wrap; gap: 0 26px; list-style: none; margin: 0; padding: 0; }
.thq .ftr-row nav a { display: inline-flex; align-items: center; min-height: 44px; color: var(--ink-soft); font: 550 15px/1 var(--sans); }
.thq .ftr-row nav a:hover { color: var(--ink); }
.thq .ftr-base { display: flex; flex-wrap: wrap; justify-content: space-between; align-items: center; gap: 6px 24px; margin-top: 22px; padding-top: 20px; border-top: 1px solid var(--line); font-size: 13px; color: var(--ink-faint); }
.thq .ftr-base .ed-note { margin-top: 0; }
@media (max-width: 760px) { .thq .ftr-row { flex-direction: column; align-items: flex-start; gap: 8px; } .thq .ftr-row nav ul { gap: 0 20px; } .thq .ftr-base { flex-direction: column; align-items: flex-start; } }

/* ── /faq ── */
.thq .fq-hero { padding: 88px 0 48px; }
.thq .fq-hero .wrap { display: grid; gap: 22px; }
.thq .fq-hero .h1 { font-size: clamp(44px, 7vw, 96px); }
.thq .search { position: relative; display: block; max-width: 560px; }
.thq .search svg { position: absolute; left: 18px; top: 50%; transform: translateY(-50%); color: var(--ink-faint); }
.thq .search input { width: 100%; height: 54px; border-radius: 999px; border: 1px solid var(--line-2); background: var(--card); padding: 0 20px 0 46px; font: 400 16px/1 var(--sans); color: var(--ink); }
.thq .fq-count, .thq .fq-empty { font-size: 14px; color: var(--ink-faint); }
.thq .topics { position: sticky; top: 72px; z-index: 20; background: var(--ground); border-top: 1px solid var(--line); border-bottom: 1px solid var(--line); }
.thq .topics .wrap { display: flex; gap: 4px; overflow-x: auto; scrollbar-width: none; padding-top: 10px; padding-bottom: 10px; }
.thq .topics a { flex: none; display: inline-flex; align-items: center; gap: 8px; min-height: 44px; padding: 0 14px; border-radius: 999px; font: 600 14px/1 var(--sans); color: var(--ink-soft); }
.thq .topics a:hover { background: var(--wash); color: var(--ink); }
.thq .topics a b { font: 500 12px/1 var(--mono); color: var(--ink-faint); }
.thq .fq-body { padding: 40px 0 120px; }
.thq details.fq-group { border-top: 1px solid var(--line); scroll-margin-top: 140px; }
.thq details.fq-group > summary { list-style: none; cursor: pointer; display: grid; grid-template-columns: minmax(0, 1fr) auto auto; gap: 18px; align-items: center; padding: 30px 0; }
.thq details.fq-group > summary::-webkit-details-marker { display: none; }
.thq .fq-title { display: grid; gap: 6px; }
.thq .fq-h2 { font: 750 clamp(26px, 3vw, 38px)/1.05 var(--sans); letter-spacing: -.035em; }
.thq .fq-desc { color: var(--ink-soft); font-size: 15.5px; }
.thq .fq-n { font: 500 12.5px/1 var(--mono); color: var(--ink-faint); }
.thq .fq-chev { width: 10px; height: 10px; border-right: 2px solid var(--ink-soft); border-bottom: 2px solid var(--ink-soft); transform: rotate(45deg); transition: transform .2s; }
.thq details.fq-group[open] .fq-chev { transform: rotate(-135deg); }
.thq details.fq-group > .faq { padding-bottom: 30px; }
.thq .fq-cta { display: flex; flex-wrap: wrap; justify-content: space-between; align-items: center; gap: 20px; margin-top: 56px; padding: 32px; border-radius: var(--r); background: var(--ground-2); }
.thq .fq-cta h2 { font: 750 26px/1.1 var(--sans); letter-spacing: -.03em; }
.thq .fq-cta p { color: var(--ink-soft); margin-top: 4px; }
@media (max-width: 700px) { .thq details.fq-group > summary { grid-template-columns: minmax(0, 1fr) auto; } .thq .fq-n { display: none; } }

/* ── reveal on scroll: only once JavaScript is there to reveal it ── */
.thq-js .reveal { opacity: 0; transform: translateY(18px); transition: opacity .8s var(--ease), transform .8s var(--ease); }
.thq-js .reveal.seen { opacity: 1; transform: none; }
/* ── the phone pass (2026-09-29, "make it really crisp and rich looking") ──
   The page ran to 39 phone screens: seven full-height phones stacked in "The
   round", deep section gaps and a tall header. The round becomes a swipeable
   day, each step a card with its real screen rising from the foot, and the
   rhythm tightens. Nothing is hidden: every step, line and screen is still
   there, one swipe apart. */
.thq a.lockup svg { margin-left: -9px; }
@media (max-width: 1000px) {
  .thq .steps { display: flex; gap: 12px; overflow-x: auto; scroll-snap-type: x mandatory; overscroll-behavior-x: contain; scrollbar-width: none; margin: 0 calc(-1 * max(20px, env(safe-area-inset-left))); padding: 2px max(20px, env(safe-area-inset-left)) 6px; scroll-padding-inline: max(20px, env(safe-area-inset-left)); }
  .thq .steps::-webkit-scrollbar { display: none; }
  .thq .steps:focus-visible { outline: 2px solid var(--brass-ui); outline-offset: 4px; }
  .thq .step { flex: 0 0 min(86%, 380px); scroll-snap-align: start; padding: 24px 22px 0; border: 1px solid var(--line); border-radius: var(--r); background: var(--card); justify-content: flex-start; overflow: hidden; }
  .thq .step-t b { font-size: 40px; }
  .thq .step h3 { margin: 16px 0 8px; font-size: 22px; }
  .thq .step p { font-size: 15px; }
  .thq .step ul { margin-top: 12px; font-size: 14px; gap: 4px; }
  /* The whole phone, never a slice of it (Ajay: "I dont like cut screens"). */
  .thq .step .inl { width: min(62%, 230px); margin: auto auto 22px; padding-top: 22px; }
}
@media (max-width: 760px) {
  .thq .hdr-in { height: 60px; }
  .thq .topics { top: 60px; }
  /* The first screen shows the product: a tighter hero lets the live board rise into view. */
  .thq .hero { padding-top: 28px; } .thq .hero .kicker { margin-bottom: 16px; }
  .thq .hero-side { gap: 18px; } .thq .hero-side p { font-size: 16.5px; }
  .thq .hero .ctas .btn { padding-left: 14px; padding-right: 14px; font-size: 15px; }
  /* The live board straight after the buttons; the proof line follows it. */
  .thq .hero .wrap { display: flex; flex-direction: column; }
  .thq .hero .stage { order: 1; margin-top: 28px; } .thq .hero .proof { order: 2; margin-top: 28px; padding-top: 16px; } .thq .hero .real { order: 3; }
  .thq .hero .ctas { flex-wrap: nowrap; } .thq .hero .ctas .btn { flex: none; }
  .thq .sec, .thq .why { padding: 64px 0; }
  .thq .shead { margin-bottom: 28px; }
  .thq .glance-col ul { grid-template-columns: minmax(0, 1fr); }
  .thq .fx-grid .f { padding: 14px 18px 15px; }
  .thq .fx-grid .f small { margin-bottom: 6px; }
  .thq .fx:has(input[name="fx"][value="competition"]:checked, input[name="fx"][value="day"]:checked, input[name="fx"][value="player"]:checked, input[name="fx"][value="money"]:checked) .f small { display: none; }
}
/* Desktop round: the steps carried small type in 620px bands, five and a half
   screens of mostly white. Larger words, shorter bands; the pinned phone still
   turns over at each one. */
@media (min-width: 1001px) {
  .thq .step { min-height: min(58vh, 500px); }
  .thq .step h3 { font-size: clamp(28px, 2.5vw, 38px); line-height: 1.12; letter-spacing: -.03em; max-width: 600px; }
  .thq .step p { font-size: 18px; line-height: 1.6; max-width: 540px; }
  .thq .step ul { font-size: 16px; }
}
/* The comparison on a phone (2026-09-29): every row and word stays; the air between
   them goes. Row labels sit tight on their cells, cells lose a line of padding,
   and the concessions and the legal note set a size down. */
@media (max-width: 700px) {
  .thq .u-row { padding: 13px 18px; gap: 2px; }
  .thq .u-row .before { font-size: 13.5px; }
  .thq .u-row .after { font-size: 15.5px; line-height: 1.4; }
  .thq .glance-col { padding: 20px 18px; }
  .thq .glance-col h3 { margin-bottom: 10px; }
  .thq .glance-col li { font-size: 14px; }
  .thq .glance-col ul { gap: 7px; }
  .thq .vs-legal { font-size: 12px; line-height: 1.5; }
  .thq .vs { margin-top: 56px; }
}
/* The two hero buttons need 380px on one row (measured); narrower phones stack them. */
@media (max-width: 379px) { .thq .hero .ctas { flex-wrap: wrap; } }
@media (prefers-reduced-motion: reduce) {
  .thq-js .reveal { opacity: 1; transform: none; transition: none; }
  .thq-js .marq-track { animation: none; }
  .thq-js .step { opacity: 1; }
  .thq .pin .scr img { transition: none; }
}
@media (min-width: 1700px) { .thq { --wrap: 1360px; } }
`
  .replace(
    "__CMP_FRAMES__",
    // One rule per frame of the comparison slider: shown when its mode AND its
    // tab are the checked ones. Generated so the frame list lives in one place.
    [
      ...["card"].map((k) => ["ap", k] as const),
      ...["championship", "coastal", "azalea"].map((k) => ["col", k] as const),
    ]
      .map(
        ([mode, k]) =>
          `.thq .compare:has(input[name="cmp-mode"][value="${mode}"]:checked):has(input[name="cmp-${mode}"][value="${k}"]:checked) .cmp-f[data-f="${mode}-${k}"] { display: grid; }`,
      )
      .join("\n"),
  )
  .replace(
    "__SHOW_FRAMES__",
    // The showcase's frames, one per tab, the same way.
    [
      "cup", "week", "calendar", "events",
    ]
      .map((k) => `.thq .show:has(input[name="show"][value="${k}"]:checked) .show-f[data-f="${k}"] { display: grid; }`)
      .join("\n"),
  );

/** The comparison slider's frames, in the order its tabs show them. Read by the page. */
// Light vs dark shows ONE screen, the full card — the one screen the page shows
// nowhere else (Ajay, 2026-09-29: "use a unique screen for the slider").
export const COMPARE_APPEARANCE = ["card"] as const;
export const COMPARE_COLOURS = ["championship", "coastal", "azalea"] as const;
