import { describe, it, expect } from "vitest";
import { parseIconName } from "@/components/Icon";
import { usedIcons, symbolId } from "../../../scripts/build-icon-sprite.mjs";
import { readVerbatim } from "./source";

/**
 * The sprite holds every icon the app asks for, and the app asks in a way the
 * sprite generator can see.
 *
 * Icons stopped being a webfont — 272.6 KB of woff2 for about 120 glyphs out
 * of roughly 1,500, `font-display: block`, so every icon in the product was
 * invisible until it arrived — and became a generated sprite of 134 symbols,
 * inline in the document.
 *
 * THE FAILURE THIS FILE EXISTS FOR IS SILENT AND SPECIFIC. A `<use href="#i-…">`
 * pointing at a symbol that is not there renders NOTHING: no error, no console
 * warning, no failed request, no layout shift — the element keeps its 1em box
 * and draws empty space. The build succeeds, every page renders, every other
 * test passes, and an icon is simply gone.
 *
 * It is not hypothetical. Converting to the sprite produced exactly that, four
 * times over, and each one got through a clean typecheck and a green suite:
 * `moon` and `circle-half` in the appearance picker, `circle` on every person
 * chip, and both weights of five player-tab icons. All four were names the
 * generator could not SEE, because they were composed at the call site out of
 * fragments — `` `ph ph-${…}` `` — rather than written out.
 */

const SPRITE = readVerbatim("src/components/IconSprite.tsx");

describe("the sprite is not stale", () => {
  it("contains every icon the source asks for", () => {
    const wanted = usedIcons("src");
    expect(wanted.length, "no icons found at all — the scan is broken").toBeGreaterThan(50);

    const missing = wanted.filter((key: string) => !SPRITE.includes(`id=\\"${symbolId(key)}\\"`));
    expect(
      missing,
      `not in the sprite: ${missing.join(", ")} — run \`node scripts/build-icon-sprite.mjs\`. ` +
        "Each of these renders as empty space with no error anywhere.",
    ).toEqual([]);
  });

  it("was generated, not hand-edited", () => {
    expect(SPRITE).toMatch(/GENERATED by scripts\/build-icon-sprite\.mjs/);
  });
});

/**
 * THE RULE THAT KEEPS THE SCAN HONEST.
 *
 * The generator reads source. A name assembled at runtime is invisible to it,
 * so the icon is missing from the sprite and draws nothing — and because the
 * expression still type-checks and still renders an element, nothing else
 * notices. Every icon name in this app is therefore a complete literal.
 *
 * Enforced rather than documented, because "keep icon names literal" is
 * exactly the sort of rule a reasonable person breaks while tidying up: a
 * template that interpolates the weight looks tidier than two spelled-out
 * strings, and it is how three of the four blanks above were written.
 */
describe("no icon name is assembled at runtime", () => {
  const SRC = readVerbatim("src/components/Icon.tsx");

  it("bans a template literal as an icon name", () => {
    const offenders: string[] = [];
    for (const file of sourceFiles()) {
      const text = readVerbatim(file);
      for (const m of text.matchAll(/<Icon\s+name=\{`[^`]*`\}/g)) {
        offenders.push(`${file}: ${m[0].slice(0, 70)}`);
      }
    }
    expect(
      offenders,
      `icon names built from fragments:\n  ${offenders.join("\n  ")}\n` +
        "The generator cannot see these, so they are missing from the sprite and " +
        "render as empty space. Write the whole name on each branch instead.",
    ).toEqual([]);
  });

  it("parses the spellings the generator produces", () => {
    // The parser and the generator must agree about what a name means, or the
    // id the component asks for is not the id the sprite defines.
    expect(parseIconName("ph ph-eye")).toEqual({ icon: "eye", weight: "regular" });
    expect(parseIconName("ph-fill ph-microphone")).toEqual({ icon: "microphone", weight: "fill" });
    expect(parseIconName("ph-bold ph-check")).toEqual({ icon: "check", weight: "bold" });
    expect(parseIconName("eye")).toEqual({ icon: "eye", weight: "regular" });
    // An empty tone is a real state in AvailabilityCalendar, not a mistake.
    expect(parseIconName("")).toEqual({ icon: "", weight: "regular" });
    expect(SRC).toContain("parseIconName");
  });
});

/** Every .ts/.tsx under src, so the ban above is swept rather than spot-checked. */
function sourceFiles(root = "src"): string[] {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { readdirSync } = require("node:fs") as typeof import("node:fs");
  const out: string[] = [];
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const path = `${root}/${entry.name}`;
    if (entry.isDirectory()) out.push(...sourceFiles(path));
    else if (/\.tsx?$/.test(entry.name)) out.push(path);
  }
  return out;
}
